[package]
authors = ["Andrew Hobden <andrew@hoverbear.org>"]
name = "ocean"
version = "0.1.0"
[dependencies]
dotenv = "0.10.0"
env_logger = "0.4.3"
error-chain = "*"
log = "0.3.8"
prettytable-rs = "0.6.7"

[dependencies.clap]
features = ["yaml"]
version = "2.24.2"

[dependencies.digitalocean]
path = "../digitalocean"
